### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by peterhodges** [wishtack/ng-steroids#1]
Firstly, thanks very much for posting this awesome library. It's just the ticket for our large Angular 1.5 app that needs a sprinkling of `onPush` style change detection for some optimizations.

What license are you releasing this under? Based on your other libraries, I'm assuming MIT. If so, would you mind adding a license file? :)

**Comment by yjaaidi** [comment]
Hi @peterhodges,

Thank you for the compliment :). Really happy that it could help you. If you have any issues or queries, don't hesitate to get in touch.

I just added the MIT license file.

Thanks !
